#!/bin/sh
# http://spin.atomicobject.com/2011/03/30/parsing-arguments-in-bash-with-getopts/
# to do: add in long flags - http://stackoverflow.com/questions/402377/using-getopts-in-bash-shell-script-to-get-long-and-short-command-line-options

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SCRIPT_FOLDER="scripts"

# -- help
usage=$(
cat <<EOF
$0 [OPTION]
-b\trun build
-c\tclean, remove temp and dist folders
-h\tdisplay help
-t\tstart up testacular server
-u\tupdate components using yeoman (bower).
EOF
)
# -v\tverbose output (not active)

BFLAG_DEFAULT=false
CFLAG_DEFAULT=false
HFLAG_DEFAULT=false
IFLAG_DEFAULT=false
TFLAG_DEFAULT=false
UFLAG_DEFAULT=false
VFLAG_DEFAULT=false
_FLAG_DEFAULT=false

while getopts "bchtuv" OPTION; do
  case "$OPTION" in
    b)
      BFLAG=true
      ;;
    c)
      CFLAG=true
      ;;
    h)
      HFLAG=true
      ;;
    i)
      IFLAG=true
      ;;
    t)
      TFLAG=true
      ;;
    u)
      UFLAG=true
      ;;
    
    v)
      VFLAG=true
      ;;
    
    *)
      _FLAG=true
      ;;
  esac
done

# set defaults
: ${BFLAG=$BFLAG_DEFAULT}
: ${CFLAG=$CFLAG_DEFAULT}
: ${HFLAG=$HFLAG_DEFAULT}
: ${IFLAG=$HFLAG_DEFAULT}
: ${TFLAG=$TFLAG_DEFAULT}
: ${UFLAG=$UFLAG_DEFAULT}
: ${VFLAG=$VFLAG_DEFAULT}
: ${_FLAG=$_FLAG_DEFAULT}

# Run command
cd $DIR

# Undefince param
if $_FLAG
then
	echo "unrecognized option"
fi

# -h Help Flag
if $HFLAG || $_FLAG
then
	echo "$usage"
fi

# -i Icon Flag
if $IFLAG || $_FLAG
then
	sh $SCRIPT_FOLDER/icon
fi

# -c Clean
if $CFLAG
then
	sh $SCRIPT_FOLDER/clean
fi

# -u Update
if $UFLAG
then
	sh $SCRIPT_FOLDER/update
fi

# -b Build
if $BFLAG
then
	sh $SCRIPT_FOLDER/build
fi

# -t Test
if $TFLAG
then
	echo "Starting testacular server\n"
	sh $SCRIPT_FOLDER/test
fi

