// Generated by CoffeeScript 1.3.3

/*
 jQuery UI Sortable plugin wrapper

 @param [ui-sortable] {object} Options to pass to $.fn.sortable() merged onto ui.config
*/


(function() {

  angular.module('ui.directives').directive('uiSortable', [
    'ui.config', function(uiConfig) {
      var options;
      options = {};
      if (uiConfig.sortable != null) {
        angular.extend(options, uiConfig.sortable);
      }
      return {
        require: '?ngModel',
        link: function(scope, element, attrs, ngModel) {
          var onStart, onUpdate, opts, _start, _update;
          opts = angular.extend({}, options, scope.$eval(attrs.uiOptions));
          if (ngModel != null) {
            onStart = function(e, ui) {
              return ui.item.data('ui-sortable-start', ui.item.index());
            };
            onUpdate = function(e, ui) {
              var end, start;
              start = ui.item.data('ui-sortable-start');
              end = ui.item.index();
              ngModel.$modelValue.splice(end, 0, ngModel.$modelValue.splice(start, 1)[0]);
              return scope.$apply();
            };
            _start = opts.start;
            opts.start = function(e, ui) {
              onStart(e, ui);
              if (typeof _start === "function") {
                _start(e, ui);
              }
              return scope.$apply();
            };
            _update = opts.update;
            opts.update = function(e, ui) {
              onUpdate(e, ui);
              if (typeof _update === "function") {
                _update(e, ui);
              }
              return scope.$apply();
            };
          }
          return element.sortable(opts);
        }
      };
    }
  ]);

}).call(this);
