#!/bin/sh

sh run -c

## Build based on Gruntfile.js ##

yeoman build --force

cd $DIR

## Clean dist folder ##
echo "Clean dist"
cd dist
cp index.web.html index.html

rm -rf img/user img/company
mkdir img/user img/company

## remove dev file types ##
rm -rf scripts styles components
# remove psd files in place for icons
find . -name "*.psd" -type f | xargs rm -f

cd ../

## Separate dist into parts (web,device,api) ##

# clean web
echo "Make & Clean dist-web"
mkdir dist-web && cp -R dist/ dist-web/
cd dist-web/

rm -rf index.php php/ index.device.html config.xml js/cordova.js
mv index.web.html index.html

cd ../

# clean device - not built yet
echo "Make & Clean dist-device"
mkdir dist-device && cp -R dist/ dist-device/
cd dist-device/

rm -rf index.php php/ index.web.html crossdomain.xml
mv index.device.html index.html

cd ../

# clean api
echo "Make & Clean dist-api"
mkdir dist-api && cp -R dist/ dist-api/
cd dist-api/

rm -rf config.xml css font img index.html index.web.html index.device.html js lang manifest.appcache view

cd ../

# zip device folder for Adobe Build upload
echo "Zipping dist-device"
(cd dist-device && zip -r ../dist-device.zip *)

echo "Completed $(date)"
