#!/bin/sh

# rebuild icons
echo "Rebuilding device icons from src/img/icon.png"
rm -rf src/img/icon/ src/img/splash/
sh scripts/icon-splash-resize src/img/icon.png white src

# https://github.com/shaurz/devo/blob/master/tools/make-ico
# brew install icoutils
icotool --create src/img/icon.png --width=16 --height=16 --output=src/img/icon/favicon.ico
