#!/bin/bash
# Generate PhoneGap icon and splash screens.
# Copyright 2013 Tom Vincent <http://tlvince.com/contact>
# Modified by will Farrell

# Requires ImageMagick
# brew install imagemagick

# 1.	A path to an icon image. Should be a square with a recommended size of 2048x2048 in any file format that ImageMagick understands (e.g. png, svg)
# 2.	A background fill colour hex string (used in splash screens). The icon will be centered on top of a single-colored background.
# 3.	Optional. A destination directory, otherwise the current working directory.

usage() { echo "usage: $0 icon colour [dest_dir]"; exit 1; }

# sh ison-splash-resize src/img/icon.png black src

[ "$1" ] && [ "$2" ] || usage
[ "$3" ] || set "$1" "$2" "."

devices=android,blackberry,ios,webos,winphone
eval mkdir -p "$3/img/{icon,splash}/{$devices}"

# Show the user some progress by outputing all commands being run.
set -x

# Explicitly set background in case image is transparent (see: #3)
convert="convert -background none"
$convert "$1" -resize 128x128 "$3/img/icon/icon.png"
$convert "$1" -resize 36x36 "$3/img/icon/android/icon-36-ldpi.png"
$convert "$1" -resize 72x72 "$3/img/icon/android/icon-72-hdpi.png"
$convert "$1" -resize 48x48 "$3/img/icon/android/icon-48-mdpi.png"
$convert "$1" -resize 96x96 "$3/img/icon/android/icon-96-xhdpi.png"
#$convert "$1" -resize 128x128 "$3/img/icon/bada/icon-128.png"
#$convert "$1" -resize 48x48 "$3/img/icon/bada-wac/icon-48-type5.png"
#$convert "$1" -resize 80x80 "$3/img/icon/bada-wac/icon-80-type4.png"
#$convert "$1" -resize 50x50 "$3/img/icon/bada-wac/icon-50-type3.png"
$convert "$1" -resize 80x80 "$3/img/icon/blackberry/icon-80.png"
$convert "$1" -resize 57x57 "$3/img/icon/ios/icon-57.png"
$convert "$1" -resize 72x72 "$3/img/icon/ios/icon-72.png"
$convert "$1" -resize 144x144 "$3/img/icon/ios/icon-72-2x.png"
$convert "$1" -resize 114x114 "$3/img/icon/ios/icon-57-2x.png"
$convert "$1" -resize 64x64 "$3/img/icon/webos/icon-64.png"
$convert "$1" -resize 48x48 "$3/img/icon/winphone/icon-48.png"
$convert "$1" -resize 173x173 "$3/img/icon/winphone/icon-173-tile.png"
$convert "$1" -resize 62x62 "$3/img/icon/winphone/icon-62-tile.png"

convert="convert $1 -background $2 -gravity center"
$convert -resize 512x512 -extent 1280x720 "$3/img/splash/android/screen-xhdpi-landscape.png"
$convert -resize 256x256 -extent 480x800 "$3/img/splash/android/screen-hdpi-portrait.png"
$convert -resize 128x128 -extent 320x200 "$3/img/splash/android/screen-ldpi-landscape.png"
$convert -resize 512x512 -extent 720x1280 "$3/img/splash/android/screen-xhdpi-portrait.png"
$convert -resize 256x256 -extent 320x480 "$3/img/splash/android/screen-mdpi-portrait.png"
$convert -resize 256x256 -extent 480x320 "$3/img/splash/android/screen-mdpi-landscape.png"
$convert -resize 128x128 -extent 200x320 "$3/img/splash/android/screen-ldpi-portrait.png"
$convert -resize 256x256 -extent 800x480 "$3/img/splash/android/screen-hdpi-landscape.png"
#$convert -resize 256x256 -extent 480x800 "$3/img/splash/bada/screen-portrait.png"
#$convert -resize 128x128 -extent 320x480 "$3/img/splash/bada-wac/screen-type3.png"
#$convert -resize 256x256 -extent 480x800 "$3/img/splash/bada-wac/screen-type4.png"
#$convert -resize 128x128 -extent 240x400 "$3/img/splash/bada-wac/screen-type5.png"
#$convert -resize 256x256 -extent 480x800 "$3/img/splash/bada-wac/screen-type5.png"
$convert -resize 128x128 -extent 225x225 "$3/img/splash/blackberry/screen-225.png"
$convert -resize 256x256 -extent 320x480 "$3/img/splash/ios/screen-iphone-portrait.png"
$convert -resize 256x256 -extent 960x640 "$3/img/splash/ios/screen-iphone-landscape-2x.png"
$convert -resize 256x256 -extent 480x320 "$3/img/splash/ios/screen-iphone-landscape.png"
$convert -resize 512x512 -extent 768x1004 "$3/img/splash/ios/screen-ipad-portrait.png"
$convert -resize 1024x1024 -extent 1536x2008 "$3/img/splash/ios/screen-ipad-portrait-2x.png"
$convert -resize 512x512 -extent 1024x783 "$3/img/splash/ios/screen-ipad-landscape.png"
$convert -resize 256x256 -extent 640x960 "$3/img/splash/ios/screen-iphone-portrait-2x.png"
$convert -resize 1024x1024 -extent 2008x1536 "$3/img/splash/ios/screen-ipad-landscape-2x.png"

convert "$1" -resize 64x64 "$3/img/splash/webos/screen-64.png"
$convert -resize 256x256 -extent 480x800 "$3/img/splash/winphone/screen-portrait.jpg"