#!/bin/sh

## Update Components via Bower ##
# Add componets to component.json
# List of components can be found at http://sindresorhus.com/bower-components/
# yeoman install __name__

#rm -rf ~/.bower # cache
rm -rf components/
yeoman update --force
