<?php
/*
This file is updated automatically as your applications is run.
*/
$permission_tests = array (
  'account_delete' => 'user_ID',
  'account_get_onboard_done' => 'user_ID',
  'account_get_session' => 'user_ID',
  'account_post_signin' => '',
  'account_post_signup' => '',
  'account_put_email_change' => 'user_ID',
  'account_put_password_change' => '',
  'company_get' => '',
  'company_get_name' => '',
  'company_get_user' => 'company_ID',
  'company_post' => 'user_ID|user_level[9]',
  'company_put' => 'user_ID|user_level[9]|company_ID',
  'company_search' => '',
  'filepicker_get_list' => 'user_ID',
  'filepicker_post_computer' => 'user_ID',
  'follow_delete' => 'user_ID',
  'follow_get' => 'user_ID',
  'follow_get_ers' => 'user_ID',
  'follow_get_friends' => 'user_ID',
  'follow_get_group' => 'user_ID',
  'follow_get_ing' => 'user_ID',
  'follow_get_referral' => 'user_ID',
  'follow_get_referrals' => 'user_ID',
  'follow_get_search' => 'user_ID',
  'follow_get_suggestions' => 'user_ID',
  'follow_put' => 'user_ID',
  'location_get' => '',
  'location_post' => 'company_ID',
  'message_get' => 'user_ID',
  'message_get_list' => 'user_ID',
  'message_post' => 'user_ID',
  'message_unread' => 'user_ID',
  'user_get' => '',
  'user_get_notify' => 'user_ID',
  'user_get_security' => 'user_ID',
  'user_put' => 'user_ID',
  'user_put_notify' => 'user_ID',
  'user_put_pgp' => 'user_ID',
  'user_search' => '',
);
?>
